steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kuda-manager', '-f', 'src/main/docker/Dockerfile.jvm', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/kuda-manager']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'kuda-manager', '--image', 'gcr.io/$PROJECT_ID/kuda-manager', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/kuda-manager